### ISSUE TITLE
Can't specify multiple vlans for the same network interface

### ISSUE THREAD

**Issue by ajf58** [rhinstaller/pykickstart#51]
I'm not sure if this is an issue with pykickstart or pyanaonda. It should be possible to configure multiple VLANs on the same interface (replicating the manual process described in [the latest networking guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Configure_802_1Q_VLAN_Tagging_Using_the_Command_Line.html) . Pykickstart's [network.py](https://github.com/rhinstaller/pykickstart/blob/master/pykickstart/commands/network.py) parses the command line so that only the last definition is used, e.g.
```network --device=em1 --vlanid=2 --vlanid=3``` 
is equivalent to
```network --device=em1 --vlanid=3```
If we try an specify multiple vlans as a comma-separated list, e.g. ```--vlanid=2,3``` then this causes pyanaconda to fail on [line 258](https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/network.py#L528) as it tries to convert ```2,3``` to an integer.

Is there currently a way to specify multiple vlans in a Kickstart file?

**Comment by clumens** [comment]
This would need to be fixed in anaconda, not pykickstart.  anaconda could interpret the vlanid string however it wants - comma separated, colon separated, whatever.  I don't think there's a way to move issues between repos, and we don't really use github issue tracking anyway.  Could you please open a bug against the anaconda component in http://bugzilla.redhat.com for this?  Thanks.
